# Nginx Reverse Proxy
FROM nginx:alpine

# Passer à un utilisateur non-root
USER nginx

# Copier la configuration Nginx
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# Exposer le port 80
EXPOSE 80

# Commande pour démarrer Nginx
CMD ["nginx", "-g", "daemon off;"]